# Generated by Django 2.1.5 on 2019-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oakfest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='country_code',
            field=models.CharField(default=2, help_text='US, IN,..', max_length=2),
            preserve_default=False,
        ),
    ]
