# Generated by Django 2.1.5 on 2019-01-19 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oakfest', '0002_site_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
