# Generated by Django 2.1.5 on 2019-01-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oakfest', '0008_sitenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='batt_area',
            field=models.DecimalField(decimal_places=5, default=None, help_text='In Square Meters', max_digits=30, null=True),
        ),
    ]
